---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - USER= #optional
      - PASS= #optional
    volumes:
      - /etc/default/transmission-config:/config
      - /srv/media:/downloads
      - /srv/media/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
